name: 'GoSquatch'
author: 'Mitch McAffee'
description: 'Go template markdown into static site'
icon: 'book-open'
color: 'green'
inputs:
  srcDir:
    description: 'Source of markdown and template files'
    required: false
    default: 'src'
  distDir:
    description: 'Destination of templated markdown html'
    required: false
    default: 'dist'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.srcDir }}
    - ${{ inputs.distDir }}