name: 'GoSquatch'
author: 'Mitch McAffee'
description: 'Go template markdown into static site'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  srcDir:
    description: 'Source of markdown and template files'
    required: false
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.srcDir }}
